name	'pnoguera/bind'
version '2.1.0'
source	'git://github.com/inkblot/puppet-bind'
author	'pnoguera'
license	'Apache 2.0'
summary 'BIND name server'
description 'A Puppet module to deploy and manage the ISC BIND server'
project_page 'https://github.com/pnoguera/puppet-bind'

dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
